### ISSUE TITLE
WIP PR 作成のための空コミット

### ISSUE THREAD

**Issue by smori1983** [smori1983/tiny-html-server#5]
ブランチを作成しただけでプッシュしても PR 作成対象のブランチにリストされない。
変更が何もない空コミットを作成してプッシュすると、リストに出るようになる。

### コマンド 

```
git commit --allow-empty
```

```
git commit --allow-empty -m ''
```

ローカルの `git` （`2.25.0`）では、コミットメッセージなしではコミットできなかった。
何か適当なコメントを入れるようにする。

### リンク

下記記事など。

- [gitで空コミットするにはgit commit --allow-empty](https://qiita.com/lni_T/items/36abcff16256282a1a6e)
- [git commit --allow-empty を使った WIP PR ワークフロー](https://qiita.com/a-suenami/items/129e09f8550f31e4c2da)

**Comment by smori1983** [comment]
@kogp112 
一応まとめておいたので、読んだらクローズしてください。

**Comment by kogp112** [comment]
読みました。クローズしますー。
