### ISSUE TITLE
ウェブサーバー最初の1歩

### ISSUE THREAD

**Issue by smori1983** [smori1983/tiny-html-server#7]
### 目標

- レンダラープロセス
  - PC 上の任意のディレクトリを選択する
  - サーバー起動ボタンをクリックする
  - #18 #19
- メインプロセス
  - `http://localhost:3000` でサーバーが起動する
  - とりあえずポートは固定
  - #10 #11 
- サーバー側のみ検証のしやすさも含めて CLI も作成する
  - #10

### 全体図

<img width="704" alt="issue_007 1" src="https://user-images.githubusercontent.com/1549175/78576017-12c3ae00-7867-11ea-9b1c-be7cb17b4033.png">

### レンダラープロセス

<img width="697" alt="issue_007 2" src="https://user-images.githubusercontent.com/1549175/80487643-2068e100-8998-11ea-86f6-193dcd2c20c0.png">

### ドキュメント

- [Electron ドキュメント](https://www.electronjs.org/docs)
  - [ipcMain](https://www.electronjs.org/docs/api/ipc-main)
  - [ipcRenderer](https://www.electronjs.org/docs/api/ipc-renderer)
  - [dialog](https://www.electronjs.org/docs/api/dialog)
- [electron-vue](https://simulatedgreg.gitbooks.io/electron-vue/ja/)

#### mori 学習用

- [jsのimportとrequireの違い](https://qiita.com/minato-naka/items/39ecc285d1e37226a283)

#### gappi 学習用
- [VueCLI babel](https://cli.vuejs.org/config/#babel)

**Comment by smori1983** [comment]
@kogp112 
使用経験があったので cli 実装に `yargs` 使ったけど、他のライブラリに差し替えてくれてもいいよ。
もしくは、`yargs` 使っていて、今の `cli.js` の書き方が古い、というような事がわかるなら、書き換えてくれてもいいよ。

**Comment by kogp112** [comment]
memo 
- [ノードES6 Babelによるプロジェクトのサポートと作成](https://riptutorial.com/ja/node-js/example/20816/%E3%83%8E%E3%83%BC%E3%83%89es6-babel%E3%81%AB%E3%82%88%E3%82%8B%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%81%A8%E4%BD%9C%E6%88%90)

**Comment by smori1983** [comment]
@kogp112 

- ディレクトリ選択部分は、テキストのペーストまたはディレクトリ選択ダイアログの2通りを可能にしておく。
- `electron` の `dialog` を使用する。
- 下記は `tiny-markdownser-server` のコード例

```html
<div class="">
  <input id="directory" type="text" value="" placeholder="directory">
  <div class="">
    <button id="directory_select" type="button">Browse</button>
  </div>
</div>
```

```js
const {dialog} = require('electron').remote;

document.getElementById('directory_select').addEventListener('click', function() {
  dialog.showOpenDialog({
    properties: ['openDirectory'],
  }, function(path) {
    document.getElementById('directory').value = path[0];
  });
});
```

**Comment by smori1983** [comment]
続き #22
