### ISSUE TITLE
nvm で指定する node のバージョンを決める

### ISSUE THREAD

**Issue by smori1983** [smori1983/tiny-html-server#8]
`nvm ls-remote`

**Comment by smori1983** [comment]
@kogp112 今だと `v12.16.1` ？

**Comment by kogp112** [comment]
stable は v10.15.3 っぽいけど
latestはそれですね

**Comment by smori1983** [comment]
https://github.com/nodejs/release

- これからアクティブ期間がメインで進行するのが v12
- メンテナンス期間がまもなく始まるのが v10

#6 で v12 以降用に修正入れてしまったのもあるので、ここは v12 で行きますか。

**Comment by smori1983** [comment]
`.nvmrc`

```
12.16.1
```
